name: 同步到gitee
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses:  同步
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:MoonlightGuardian/fengfan.github.io"
        # 目标仓库
        destination-repo: "git@gitee.com:Know/fengfan"
  
